# Generated by Django 3.2 on 2022-08-30 10:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Catagory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='title')),
                ('description', models.TextField(blank=True, verbose_name='desctiption')),
                ('avatar', models.ImageField(blank=True, upload_to='catagories/', verbose_name='avator')),
                ('is_enable', models.BooleanField(default=True, verbose_name='status')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='create date')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='updated date')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.catagory', verbose_name='parent')),
            ],
            options={
                'verbose_name': 'Catagory',
                'verbose_name_plural': 'Catagories',
                'db_table': 'catagories',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='title')),
                ('description', models.TextField(blank=True, verbose_name='desctiption')),
                ('avatar', models.ImageField(blank=True, upload_to='products/', verbose_name='avator')),
                ('is_enable', models.BooleanField(default=True, verbose_name='status')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='create date')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='updated date')),
                ('catagories', models.ManyToManyField(blank=True, to='products.Catagory', verbose_name='catagories')),
            ],
            options={
                'verbose_name': 'product',
                'verbose_name_plural': 'products',
                'db_table': 'products',
            },
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='title')),
                ('file', models.FileField(upload_to='file/%y/%m/%d/', verbose_name='file')),
                ('is_enable', models.BooleanField(default=True, verbose_name='status')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='create date')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='updated date')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product', verbose_name='product')),
            ],
            options={
                'verbose_name': 'file',
                'verbose_name_plural': 'files',
                'db_table': 'files',
            },
        ),
    ]
